@Host = http://localhost:5156

### Hello!
GET {{Host}}/hello
Accept: application/json

### get all books
GET {{Host}}/api/books
Accept: application/json

### get book by id
GET {{Host}}/api/books/1
Accept: application/json
