@Host = http://localhost:5156

### Hello!
GET {{Host}}/hello
Accept: application/json

### get all books
GET {{Host}}/api/books
Accept: application/json

### get book by id
GET {{Host}}/api/books/1
Accept: application/json

### create new book
POST {{Host}}/api/books
Content-type: application/json

{
  "id": 0,
  "title": "NEW Clean Code",
  "author": "Robert C. Martin",
  "year": 2026,
  "price": 35.99
}

### update a book
PUT {{Host}}/api/books/1
Content-type: application/json

{
  "id": 1,
  "title": "UPDATED Clean Code",
  "author": "Robert C. Martin",
  "year": 2008,
  "price": 35.99
}